---
- name: Play for 
  hosts: all
  become: true
  remote_user: quantumcrow
  gather_facts: true
  tasks:

# Individual packages
    
    - name: pkg
      ansible.builtin.dnf:
        name: pkg
        state: present

# Enable services

    - name: service
      systemd:
        name: service_name
        state: started
        enabled: yes
