---
- name: Play for installing packages
  hosts: all
  become: true
  remote_user: quantumcrow
  gather_facts: true
  tasks:

# Individual packages

    - name: Install firewalld
      ansible.builtin.dnf:
        name: firewalld.noarch
        state: present
    - name: Install git
      ansible.builtin.dnf:
        name: git
        state: present
    - name: Install vim-ehanced
      ansible.builtin.dnf:
        name: vim-enhanced-2:8.2.2637-20.el9_1.x86_64
        state: present
    - name: Install strace
      ansible.builtin.dnf:
        name: strace-5.18-2.el9.x86_64
        state: present
    - name: Install epel-release
      ansible.builtin.dnf:
        name: epel-release-9-7.el9.noarch
        state: present
