---
- name: Play for installing packages
  hosts: all
  become: true
  remote_user: quantumcrow
  gather_facts: true
  tasks:

# Individual packages

    - name: Install podman
      ansible.builtin.dnf:
        name: podman-2:4.6.1-5.el9.x86_64
        state: present
    - name: Install podman-compose
      ansible.builtin.dnf:
        name: podman-compose-1.0.6-3.el9.noarch
        state: present
