---
- name: Play for installing web packages
  hosts: all
  become: true
  remote_user: quantumcrow
  gather_facts: true
  tasks:

# Individual packages

    - name: Remove postgresql
      ansible.builtin.dnf:
        name: postgresql
        state: absent
    - name: Remove pgadmin repo
      ansible.builtin.command: rpm -e pgadmin4-redhat-repo
    - name: Remove pgadmin
      ansible.builtin.dnf:
        name: pgadmin4-web
        state: absent
