---
- name: Play for installing starting packages and enabling CRB for the epel-release
  hosts: all
  become: true
  remote_user: quantumcrow
  gather_facts: true
  tasks:

# Individual packages
    - name: Install epel-release
      ansible.builtin.dnf:
        name: epel-release
        state: present
        enablerepo: epel
    - name: Enable epel-release
      ansible.builtin.command: dnf config-manager --set-enabled crb
    - name: Install packages
      package:
        name: "{{item}}"
        state: present
      loop:
        - firewalld
        - git
        - vim-enhanced
        - strace
        - fd-find
        - bat
        - fzf
