---
# tasks file for user_setup

- name: Create user
  user:
    name: corvidae
    state: present
    groups: wheel
    shell: /bin/bash

- name: Install applications
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - curl
    - wget
