---
- name: Play for adding repos and installing their apps
  hosts: localhost
  become: true
  remote_user: quantumcrow
  gather_facts: true
  tasks:

# Individual packages
    
    - name: Install librewolf
      ansible.builtin.yum_repository:
        name: librewolf
        description: Librewolf repo
        baseurl: https://repo.librewolf.net/librewolf.repo