---
- name: Play for install apps from archives
  hosts: localhost
  become: true
  remote_user: quantumcrow
  gather_facts: true
  tasks:

# Individual packages
    
    - name: Unarchive jetbrains-toolbox
      ansible.builtin.unarchive:
        src: https://download.jetbrains.com/toolbox/jetbrains-toolbox-2.5.4.38621.tar.gz
        dest: /home/quantumcrow/Downloads/
        remote_src: true