---
- name: Play for installing packages
  hosts: all
  become: true
  remote_user: quantumcrow
  gather_facts: true
  tasks:

# Individual packages

    - name: Install podman
      ansible.builtin.dnf:
        name: podman
        state: present
    - name: Install podman-compose
      ansible.builtin.dnf:
        name: podman-compose
        state: present
    - name: Install podman-docker
      ansible.builtin.dnf:
        name: podman-docker
        state: present
