---
- name: Play for installing starting packages and enabling CRB for the epel-release
  hosts: all
  become: true
  remote_user: quantumcrow
  gather_facts: true
  tasks:

# Individual packages   
    - name: Install epel-release
      ansible.builtin.dnf:
        name: epel-release
        state: present
        enablerepo: epel
    - name: Enable epel-release
      ansible.builtin.command: dnf config-manager --set-enabled crb
    - name: Install firewalld
      ansible.builtin.dnf:
        name: firewalld.noarch
        state: present
    - name: Install git
      ansible.builtin.dnf:
        name: git
        state: present
    - name: Install vim-ehanced
      ansible.builtin.dnf:
        name: vim-enhanced
        state: present
    - name: Install strace
      ansible.builtin.dnf:
        name: strace
        state: present
    - name: Install fd
      ansible.builtin.dnf:
        name: fd
        state: present
