---
- name: Play for creating users
  hosts: all
  become: true
  remote_user: root
  gather_facts: true

  vars:
    username: quantumcrow

  tasks:
    - name: Delete user
      ansible.builtin.user:
        name: "{{ username }}"
        state: absent
        remove: true
