---
- name: Play for managing firewall ports
  hosts: all
  become: true
  remote_user: quantumcrow
  gather_facts: true
  tasks:

# Open ports
    - name: Open http
      ansible.posix.firewalld:
        zone: public
        port: "{{ item }}"
        permanent: true
        immediate: true
        state: disabled
      loop:
        - 80/tcp
        - 443/tcp

# Reload firewalld
    - name: Reload firwalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
